export const ImageSource = {
    bell: require('.././../assets/images/bell.png'),
    busOutline: require('.././../assets/images/busOutline.png'),
    calenderBlue: require('.././../assets/images/calenderBlue.png'),
    call: require('.././../assets/images/call.png'),
    banner: require('.././../assets/images/banner.png'),
    clock: require('.././../assets/images/clock.png'),
    cross: require('.././../assets/images/cross.png'),
    eyeOff: require('.././../assets/images/eyeOff.png'),
    gpsIcon: require('.././../assets/images/gpsIcon.png'),
    greenCheckbox: require('.././../assets/images/greenCheckbox.png'),
    HistoryIcon: require('.././../assets/images/HistoryIcon.png'),
    Home: require('.././../assets/images/Home.png'),
    homeIcon: require('.././../assets/images/homeIcon.png'),
    leftArrow: require('.././../assets/images/leftArrow.png'),
    menu: require('.././../assets/images/menu.png'),
    office: require('.././../assets/images/office.png'),
    rightTickfilled: require('.././../assets/images/rightTickfilled.png'),
    searhIcon: require('.././../assets/images/searhIcon.png'),
    seatOutline: require('.././../assets/images/seatOutline.png'),
    shuttel: require('.././../assets/images/shuttel.png'),
    sun: require('.././../assets/images/sun.png'),
    ticket: require('.././../assets/images/ticket.png'),
    updownArrow: require('.././../assets/images/updownArrow.png'),
    wallet: require('.././../assets/images/wallet.png'),
    WalletIcon: require('.././../assets/images/WalletIcon.png'),
    weather: require('.././../assets/images/weather.png'),
    bloodOutline: require('.././../assets/images/blood_outline.png'),
    calenderOutline: require('.././../assets/images/calender_outline.png'),
    callOutline: require('.././../assets/images/call_outline.png'),
    emailOutline: require('.././../assets/images/email_outline.png'),
    genderOutline: require('.././../assets/images/gender_outline.png'),
    userOutline: require('.././../assets/images/user_outline.png'),
    // profile section
    bookmarkOutline: require('.././../assets/images/bookmarkOutline.png'),
    logoutOutline: require('.././../assets/images/logoutOutline.png'),
    megaPhone: require('.././../assets/images/megaPhone.png'),
    rightTriangleArrow: require('.././../assets/images/rightTriangleArrow.png'),
    settingsOutline: require('.././../assets/images/settingsOutline.png'),
    suggestYourStops: require('.././../assets/images/suggestYourStops.png'),
    bellOutline: require('.././../assets/images/bell_outline.png'),
    falg: require('.././../assets/images/flag.png'),
    whatsapp: require('.././../assets/images/whatsapp.png'),
    delete: require('.././../assets/images/delete.png'),
    checkCircle: require('.././../assets/images/checkCircle.png'),
    checkSquare: require('.././../assets/images/checkSquare.png'),
    uncheckCircle: require('.././../assets/images/uncheckCircle.png'),
     edit: require('.././../assets/images/edit.png'),

      // history section
  busOnTrack: require('.././../assets/images/bus_on_track.png'),
  busYellow: require('.././../assets/images/bus_yellow.png'),
  SeatYellow: require('.././../assets/images/seat_yellow.png'),

  shareBlue: require('.././../assets/images/share.png'),
  chevron: require('.././../assets/images/chevron.png'),
  chevronRight: require('.././../assets/images/chevron_right.png'),
  chatIcon: require('.././../assets/images/chat.png'),

  steering: require('.././../assets/images/steering.png'),
  mapPin: require('.././../assets/images/map_pin.png'),
  languages: require('.././../assets/images/languages.png'),

  scan: require('.././../assets/images/scan.png'),
  qrCodePlaceholder: require('.././../assets/images/qr_code.png'),
  swapPoints: require('.././../assets/images/swap_points.png'),
};
