export const ScreenNames = {
  DASHBOARD_SCREEN: 'DashboardScreen',
  HOME_SCREEN: 'HomeScreen',
  WALLET_SCREEN: 'WalletScreen',
  HISTORY_SCREEN: 'HistoryScreen',
  TRANSACTION_HISTORY_SCREEN: 'TransactionHistoryScreen',
  TRANSACTION_DETAIL_SCREEN: 'TransactionDetailScreen',
  SAVED_PLACES_SCREEN: 'SavedPlacesScreen',
  ADD_EDIT_LOCATION_SCREEN: 'AddEditLocationScreen',
  POLICY_SCREEN: 'PolicyScreen',
  RENT_A_BUS_SCREEN: 'RentABusScreen',
  ACCOUNT_SETTING_SCREEN: 'AccountSettingScreen',
  SET_PROFILE_SCREEN: 'SetYourProfileScreen',
  MAIN_SCREEN: 'MainScreen',
  LOGIN_SCREEN: 'LoginScreen',
  VIEW_PROFILE: 'ViewProfileScreen',
  SUGGEST_YOUR_STOPS: 'SuggestYourStopsScreen',
  MY_SUGGESTIONS: 'MySuggestionsScreen',
  BUS_SELECTION_SCREEN: 'BusSelectionScreen',
  TRACK_RIDE_SCREEN: 'TrackRideScreen',
  TICKET_DETAIL_SCREEN: 'TicketDetailScreen',
  FULL_ROUTE_SCREEN: 'FullRouteScreen',
  NOTIFICATION_SCREEN: 'NotificationScreen',
  CONFIRM_BOOKING_DETAILS: 'ConfirmBookingDetailsScreen',
  BOOKING_OPTIONS: 'BookingOptionsScreen',
  PAYMENT_OPTIONS: 'PaymentOptionsScreen',
  BOOKING_SUCCESS: 'BookingSuccessScreen',
  SELF_BOARD_SCANNER: 'SelfBoardScannerScreen',
  SELF_BOARD_SUCCESS: 'SelfBoardSuccessScreen',
  SELF_BOARD_ERROR: 'SelfBoardErrorScreen',
  SET_COMMUTE: 'SetCommuteScreen', // first commute
  FIND_COMMUTE: 'FindCommute', // second time
  SEAT_SELECTION: 'SeatSelectionScreen',
  TICKETS_SCREEN: 'TicketsScreen',
  RENTAL_REQUESTS_SCREEN: 'RentalRequestsScreen',
  RENTAL_DETAILS_SCREEN: 'RentalDetailsScreen',
  SPLASH_SCREEN: 'SplashScreen',
  DUMMY: "DUMMY"
} as const;
